### ISSUE TITLE
Some findings for version2

### ISSUE THREAD

**Issue by cyrusmsk** [bachmeil/embedrv2#1]
First of all, it should be somehow added to the dependencies that some package for 'locate' command should be installed.

I've used Manjaro distribution. I found two possible packages: mlocate and plocate.
Both packages (after I tried to run in R command 'dubNewShared()') gave:
**Warning message:
In system("locate -b '\\libR.so' -l 1", intern = TRUE) :
  running command 'locate -b '\libR.so' -l 1' had status 1**

I'm not sure if this is 'ok'

R version 4.1.3

Also 'dubNew()' still has link to embedr, not to embedr2.

For installation of the package I've used install_github("bachmeil/embedrv2")

**Comment by bachmeil** [comment]
I'm currently in the process of updating everything. This is still work in progress. I'd recommend using the original embedr package if you can. Hopefully I'll have time to finish and release embedrv2 soon.
